
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 28 19:16:54 EST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 22;
  public static final int FROM = 21;
  public static final int AND = 29;
  public static final int COMPARISON = 10;
  public static final int SELECT = 25;
  public static final int RPAREN = 4;
  public static final int DECIMAL = 28;
  public static final int SEMI = 6;
  public static final int STAR = 8;
  public static final int PERIOD = 2;
  public static final int ERROR = 7;
  public static final int NAME = 9;
  public static final int VARIABLE = 13;
  public static final int LPAREN = 3;
  public static final int TABLE = 15;
  public static final int VARCHAR = 26;
  public static final int STRING = 12;
  public static final int CREATE = 14;
  public static final int COMMA = 5;
  public static final int INSERT = 17;
  public static final int EOF = 0;
  public static final int NUMBER = 11;
  public static final int VALUES = 19;
  public static final int SET = 24;
  public static final int DATABASE = 16;
  public static final int error = 1;
  public static final int INTEGER = 27;
  public static final int UPDATE = 23;
  public static final int DELETE = 20;
  public static final int PATH = 30;
  public static final int INTO = 18;
}

